# Generated by Django 4.1.2 on 2023-01-28 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line_1", models.CharField(max_length=100, null=True)),
                ("address_line_2", models.CharField(max_length=100, null=True)),
                (
                    "profile_picture",
                    models.ImageField(null=True, upload_to="userprofile/"),
                ),
                ("city", models.CharField(max_length=30, null=True)),
                ("state", models.CharField(max_length=30, null=True)),
                ("country", models.CharField(max_length=30, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
